MVN-50 Implement DTO entities
anastaciatimohova/Movienote pull request #1
Opened 2021-11-03 14:51 UTC by NadezhdaPenkrat

2021-11-21 14:30 UTC, RomanKashenok requested changes

2021-11-21 14:30 UTC, RomanKashenok commented on src/main/java/com/movienote/dto/GenreDto.java
> +@JsonAutoDetect
зачем эта аннотация?

2021-11-21 14:30 UTC, RomanKashenok commented on src/main/java/com/movienote/dto/GenreDto.java
> +@AllArgsConstructor
где-то создаешь объект сразу?

2021-11-21 14:30 UTC, RomanKashenok commented on src/main/java/com/movienote/dto/GenreDto.java
> +    public GenreDto toDto(Genre genre) {
а где ты используешь это дто так, что его самой надо составлять?

2021-11-21 14:30 UTC, RomanKashenok commented on src/main/java/com/movienote/dto/MovieDto.java
> +public class MovieDto {
все аналогично предыдущему

2021-11-21 14:30 UTC, RomanKashenok commented on src/main/java/com/movienote/dto/RoleDto.java
> +public class RoleDto {
аналогично предыдущему

2021-11-22 12:01 UTC, NadezhdaPenkrat commented on src/main/java/com/movienote/dto/GenreDto.java
> +    public GenreDto toDto(Genre genre) {
точно, есть же только внешний ресурса

2021-12-06 09:58 UTC, RomanKashenok approved these changes

2021-12-07 08:39 UTC, merged